[build-system]
requires = ["setuptools>=68", "wheel", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "pxrr"
version = "0.2.0"
description = "Package for pseudo X-ray reflectivity and GIXOS data analysis"
readme = "README.rst"
authors = [{ name = "AUTHORS.rst" }]
license = { file = "LICENSE" }
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
]
requires-python = ">=3.10,<3.14"
dependencies = [
    "ipython",
    "numpy>=1.24",
    "scipy>=1.10",
    "matplotlib>=3.7",
    "pandas>=2.0",
    "h5py>=3.8",
    "ruamel.yaml>=0.17",
    "joblib>=1.3",
    "orsopy>=1.2",
    "xray-general-io @ git+https://gitlab.desy.de/petra-iii/p08/data-process/xray_general_io.git",
]

[project.optional-dependencies]
p08 = [
    "p08-general @ git+https://gitlab.desy.de/petra-iii/p08/data-process/p08_general.git",
]

[project.urls]
"Homepage" = "https://github.com/nsls2/pxrr"
"Bug Tracker" = "https://github.com/nsls2/pxrr/issues"

[tool.setuptools.packages.find]
where = ["."]
include = ["pseudo_xrr*"]

[tool.setuptools_scm]
version_scheme = "guess-next-dev"
local_scheme = "no-local-version"
