# metadata.yaml
# data type: 2d gixs or 1d gixos
facility: "PETRA III/P08"
datatype: "2d gixs"
geometrical_correction: True

paths:
  gixs_path: "/asap3/petra3/gpfs/p08/2026/data/11024557/processed/GID/"         
  path_out: "../output/p08_2d/"

measurements:
    sample:      "GID_dppc_22degc"
    scan:        15
    bkgsample:   "GID_chamber_bkg"
    bkgscan:     8
    flux:          1.2e11 # ct/s
    cttime_sample: 30 # seconds
    cttime_bkg:    30 # seconds

instrument:
    energy:   15000     # must
    alpha:  0.07      # must
    Ddet:     443.7     # optional, for geometrical correction, footprint correction
    pixel:    0.075     # optional, for geometrical correction
    DSpxHW:  6          # [pixels] mandatory for 2d gixs, half width of the integrating region on detector
    #HWtth:    0.004     # [deg] optional, mandatory for 1d gixs, half width of the GIXOS pixel in tth
    footprint: 60       # [mm] optional, for footprint correction

qxy0: [0, 0.005, 0.015, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1, 0.11, 0.12, 0.14, 0.16, 0.35, 0.37, 0.39, 0.41, 0.43, 0.45]
qxy_bkg: 0.3

PseudoR:
    qxy0_select_idx: [2,3,4,5,6]
    # resolution_mode 0: circular size [1/A], 1: slit, size [mm]
    resolution_mode: 0      #
    resolution_HW:  0.0002  # mode=0: float, mode=1: [v_HW, h_HW]
    # the following are option, only relevant at slit resolution mode (resolution_mode = 1)
    energy:             # [eV], None, or float
    Ddet:               # [mm]
    bkg_mode:           # None, 0: phi (h) off, 1: beta (v) off
    bkg_off:            # [mm], center from specular

sample_params:
    Qc:       0.0218    # critical angle in 1/A
    tension:     0.038       # N/m
    temperature: 295        # K
    kappa: 13   # kbT
    amin: 5     # molecular distance

dependency:
    qz_selected: [0.1, 0.15]
    kappa_deviation: 3
  
